config/routes.rb
Rails.application.routes.draw do
  resources :swipes
  resources :investors
  resources :founders
  resources :pages

  get '/favourites' => 'swipes#index'

  # root :to => 'sessions#new'
  root :to => 'founders#index'
  
  get '/login' => 'sessions#new'

  get '/investor_signup' => 'investors#new'

  get '/founder_signup' => 'founders#new'

  post '/investor_login' => 'sessions#investor_login'
  post '/founder_login' => 'sessions#founder_login'

  delete '/investor_logout' => 'sessions#investor_logout'
  delete '/founder_logout' => 'sessions#founder_logout'

  post '/founders/:id/like' => 'founders#like'

end

app/models/swipe.rb
# == Schema Information
#
# Table name: swipes
#
#  id          :integer          not null, primary key
#  founder_id  :integer
#  investor_id :integer
#  favourite   :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Swipe < ActiveRecord::Base
  belongs_to :investor
  belongs_to :founder
end

app/controllers/swipes_controller.rb
class SwipesController < ApplicationController
  before_action :set_swipe, only: [:show, :edit, :update, :destroy]

  # GET /swipes
  # GET /swipes.json
  def index
    @swipes = @current_investor.swipes
  end

  # GET /swipes/1
  # GET /swipes/1.json
  def show

  end

  # GET /swipes/new
  def new
    @swipe = Swipe.new
  end

  # GET /swipes/1/edit
  def edit
  end

  # POST /swipes
  # POST /swipes.json
  def create
    @swipe = Swipe.new(swipe_params)
    respond_to do |format|
      if @swipe.save
        format.html { redirect_to @swipe, notice: 'Swipe was successfully created.' }
        format.json { render :show, status: :created, location: @swipe }
      else
        format.html { render :new }
        format.json { render json: @swipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /swipes/1
  # PATCH/PUT /swipes/1.json
  def update
    respond_to do |format|
      if @swipe.update(swipe_params)
        format.html { redirect_to @swipe, notice: 'Swipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @swipe }
      else
        format.html { render :edit }
        format.json { render json: @swipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /swipes/1
  # DELETE /swipes/1.json
  def destroy
    @swipe.destroy
    respond_to do |format|
      format.html { redirect_to swipes_url, notice: 'Swipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_swipe
      @swipe = Swipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def swipe_params
      params.require(:swipe).permit(:founder_id, :investor_id, :favourite)
    end
end

app/helpers/swipes_helper.rb
module SwipesHelper
end

app/views/swipes/_form.html.erb
<%= form_for(@swipe) do |f| %>
  <% if @swipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@swipe.errors.count, "error") %> prohibited this swipe from being saved:</h2>

      <ul>
      <% @swipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :founder_id %><br>
    <%= f.number_field :founder_id %>
  </div>
  <div class="field">
    <%= f.label :investor_id %><br>
    <%= f.number_field :investor_id %>
  </div>
  <div class="field">
    <%= f.label :favourite %><br>
    <%= f.check_box :favourite %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/swipes/index.html.erb
<div class="container">
  <div class="row">
    <div class="panel panel-default widget">
    <div class="panel-heading"><span class="glyphicon glyphicon-comment"></span><h3 class="panel-title">Favourites</h3></div>

    <% @swipes.each do |swipe| %>
      
      <div class="panel-body">

          <div class="col-xs-6 col-sm-4">
            <img src="<%= swipe.founder.profile_picture %>" alt="" class="img-circle" style="max-height: 100px; max-width: 100px;"/>
          </div> 

          <div class="col-xs-6 col-sm-4">
            <p><%= link_to swipe.founder.company_name, founders_path %></p>
          </div> 

          <div class="col-xs-6 col-sm-4">
            <a  href="#" class="btn btn-sm btn-hover btn-primary" href="#reply" >
              <span class="glyphicon glyphicon-share-alt" style="padding-right:3px;"></span>Message</a>
            <a class="btn btn-sm btn-hover btn-danger" <%= link_to 'Delete', swipe, method: :delete, data: { confirm: 'Are you sure?' } %> </a>
          </div>

      </div>
    
    <% end %>
    </div>
  </div>
</div>

app/views/swipes/new.html.erb
<h1>New Swipe</h1>

<%= render 'form' %>

<%= link_to 'Back', swipes_path %>

app/views/swipes/show.html.erb
<p id="notice"><%= notice %></p>

<p> This is the editing form</p>
<p>
  <strong>Founder:</strong>
  <%= @swipe.founder_id %>
</p>

<p>
  <strong>Investor:</strong>
  <%= @swipe.investor_id %>
</p>

<p>
  <strong>Favourite:</strong>
  <%= @swipe.favourite %>
</p>

<%= link_to 'Edit', edit_swipe_path(@swipe) %> |
<%= link_to 'Back', swipes_path %>