config/routes.rb
Rails.application.routes.draw do
  resources :swipes
  resources :investors
  resources :founders
  resources :pages

  get '/favourites' => 'swipes#index'

  # root :to => 'sessions#new'
  root :to => 'founders#index'
  
  get '/login' => 'sessions#new'

  get '/investor_signup' => 'investors#new'

  get '/founder_signup' => 'founders#new'

  post '/investor_login' => 'sessions#investor_login'
  post '/founder_login' => 'sessions#founder_login'

  delete '/investor_logout' => 'sessions#investor_logout'
  delete '/founder_logout' => 'sessions#founder_logout'

  post '/founders/:id/like' => 'founders#like'

end

app/models/investor.rb
# == Schema Information
#
# Table name: investors
#
#  id              :integer          not null, primary key
#  name            :text
#  company_name    :text
#  email_address   :text
#  password_digest :text
#  website         :text
#  title           :string
#  profile_picture :text
#  investor_id     :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Investor < ActiveRecord::Base
  has_secure_password
  has_many :swipes
  # has_many :messages 
  # messages belongs_to :investor through => :favourites
end

app/controllers/investors_controller.rb
class InvestorsController < ApplicationController
  before_action :set_investor, only: [:show, :edit, :update, :destroy]

  # GET /investors
  # GET /investors.json
  def index
    @investors = Investor.all
  end

  # GET /investors/1
  # GET /investors/1.json
  def show
  end

  # GET /investors/new
  def new
    @investor = Investor.new
  end

  # GET /investors/1/edit
  def edit
  end

  # POST /investors
  # POST /investors.json
  def create
    @investor = Investor.new(investor_params)

    unless params[:file] == ""
      image = Cloudinary::Uploader.upload( params[:file] )
      @investor.profile_picture = image["url"]
    end

    respond_to do |format|
      if @investor.save
        format.html { redirect_to @investor, notice: 'Investor was successfully created.' }
        format.json { render :show, status: :created, location: @investor }
      else
        format.html { render :new }
        format.json { render json: @investor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investors/1
  # PATCH/PUT /investors/1.json
  def update

    unless params[:file] == ""
      image = Cloudinary::Uploader.upload( params[:file] )
      @investor.profile_picture = image["url"]
    end

    respond_to do |format|
      if @investor.update(investor_params)
        format.html { redirect_to @investor, notice: 'Investor was successfully updated.' }
        format.json { render :show, status: :ok, location: @investor }
      else
        format.html { render :edit }
        format.json { render json: @investor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investors/1
  # DELETE /investors/1.json
  def destroy
    @investor.destroy
    respond_to do |format|
      format.html { redirect_to investors_url, notice: 'Investor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investor
      @investor = Investor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def investor_params
      params.require(:investor).permit(:name, :company_name, :email_address, :password, :password_co, :website, :title, :profile_picture, :investor_id)
    end
end

app/helpers/investors_helper.rb
module InvestorsHelper
end

app/views/investors/_form.html.erb
<%= form_for(@investor) do |f| %>
  <% if @investor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@investor.errors.count, "error") %> prohibited this investor from being saved:</h2>

      <ul>
      <% @investor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :company_name %><br>
    <%= f.text_area :company_name %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.text_area :email_address %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_area :website %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :profile_picture %><br>
    <%= f.cl_image_upload :profile_picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/investors/edit.html.erb
<div class="container">
  <div class="login-signup">
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="home">
        <div class="row">

          <div class="col-sm-6 mobile-pull">
              <article role="login">
                <h3 class="text-center"><i class="fa fa-lock"></i>Update Investor</h3>
      
                <%= form_for(@investor, :method => :put) do |f| %> 

                  <div class="form-group">
                    <%= f.label :profile_picture %><br>
                    <%= f.cl_image_upload :profile_picture %>
                  </div>

                  <div class="form-group">
                    <%= f.text_field :name, :placeholder => "Name", class: "form-control" %> 
                  </div>

                  <div class="form-group">
                    <%= f.text_field :title, :placeholder => "Title", class: "form-control" %> 
                  </div>

                  <div class="form-group">
                    <%= f.text_field :company_name, :placeholder => "Company Name", class: "form-control" %> 
                  </div>

                  <div class="form-group">
                    <%= f.text_field :website, :placeholder => "Website", class: "form-control" %> 
                  </div>

                  <div class="form-group">
                    <%= f.email_field :email_address, :placeholder => "Email", class: "form-control" %> 
                  </div>

                  <div class="form-group">
                    <%= f.password_field :password, :placeholder => "Password", class: "form-control"%> 
                  </div>

                  <div class="form-group">
                    <%= f.password_field :password_confirmation, :placeholder => "Password Confirmation", class: "form-control"%> 
                  </div>

                  <div class="actions">
                    <%= f.submit "UPDATE", class: "btn btn-submit btn-success btn-block" %>
                  </div>

                    <% end %>

              </article>
            </div>

          </div>
          <!-- end of row -->
        </div>
        <!-- end of home -->
  </div>

app/views/investors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Investors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Company name</th>
      <th>Email address</th>
      <th>Password digest</th>
      <th>Website</th>
      <th>Title</th>
      <th>Profile picture</th>
      <th>Investor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @investors.each do |investor| %>
      <tr>
        <td><%= investor.name %></td>
        <td><%= investor.company_name %></td>
        <td><%= investor.email_address %></td>
        <td><%= investor.password_digest %></td>
        <td><%= investor.website %></td>
        <td><%= investor.title %></td>
        <td><%= investor.profile_picture %></td>
        <td><%= investor.investor_id %></td>
        <td><%= link_to 'Show', investor %></td>
        <td><%= link_to 'Edit', edit_investor_path(investor) %></td>
        <td><%= link_to 'Destroy', investor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Investor', new_investor_path %>

app/views/investors/new.html.erb
<div class="container">
  <div class="login-signup">
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="home">
        <div class="row">

          <div class="col-sm-6 mobile-pull">
              <article role="login">
                <h3 class="text-center"><i class="fa fa-lock"></i>Investor Registration</h3>
      
                <%= form_for(:session, url: investor_login_path) do |f| %> 

                  <div class="form-group">
                    <%= f.label :profile_picture %><br>
                    <%= f.cl_image_upload :profile_picture %>
                  </div>

                  <div class="form-group">
                    <%= f.text_field :name, :placeholder => "Name", class: "form-control" %> 
                  </div>

                  <div class="form-group">
                    <%= f.text_field :title, :placeholder => "Title", class: "form-control" %> 
                  </div>

                  <div class="form-group">
                    <%= f.text_field :company_name, :placeholder => "Company Name", class: "form-control" %> 
                  </div>

                  <div class="form-group">
                    <%= f.text_field :website, :placeholder => "Website", class: "form-control" %> 
                  </div>

                  <div class="form-group">
                    <%= f.email_field :email_address, :placeholder => "Email", class: "form-control" %> 
                  </div>

                  <div class="form-group">
                    <%= f.password_field :password, :placeholder => "Password", class: "form-control"%> 
                  </div>

                  <div class="form-group">
                    <%= f.password_field :password_confirmation, :placeholder => "Password Confirmation", class: "form-control"%> 
                  </div>

                  <div class="form-group">
                    <%= link_to 'REGISTER', founder_signup_path, class: "btn btn-success btn-block" %>
                  </div>
                    <div class="actions">
                    <%= f.submit "Register", class: "btn btn-submit btn-success btn-block" %>
                  </div>

                    <% end %>

              </article>
            </div>

          </div>
          <!-- end of row -->
        </div>
        <!-- end of home -->
  </div>
</div>

app/views/investors/show.html.erb
<div class="container">
  <div class="login-signup">
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="home">
        <div class="row">

          <div class="col-sm-6 mobile-pull">
              <article role="login">
                <h3 class="text-center"><i class="fa fa-lock"></i>My Profile</h3>
            
                <center>
                  <a href="#aboutModal" data-toggle="modal" data-target="#myModal"><img src="<%= @investor.profile_picture %>" name="aboutme" width="140" height="140" class="img-circle"></a>
                  <h1><%= @investor.name %></h1>
                  <h1><%= @investor.company_name %></h1>
                  <h1><%= @investor.title %></h1>
                  <h1><%= @investor.email_address %></h1>
                  <h1><%= @investor.website %></h1>
                  <%= link_to 'Edit', edit_investor_path(@investor) %>
                </center>
            </article>
          </div>
        </div>
<!-- end of row -->
      </div>
<!-- end of home -->
    </div>
  x</div>
</div>