config/routes.rb
Rails.application.routes.draw do
  resources :swipes
  resources :investors
  resources :founders
  resources :pages

  get '/favourites' => 'swipes#index'

  # root :to => 'sessions#new'
  root :to => 'founders#index'
  
  get '/login' => 'sessions#new'

  get '/investor_signup' => 'investors#new'

  get '/founder_signup' => 'founders#new'

  post '/investor_login' => 'sessions#investor_login'
  post '/founder_login' => 'sessions#founder_login'

  delete '/investor_logout' => 'sessions#investor_logout'
  delete '/founder_logout' => 'sessions#founder_logout'

  post '/founders/:id/like' => 'founders#like'

end

app/models/founder.rb
# == Schema Information
#
# Table name: founders
#
#  id               :integer          not null, primary key
#  name             :text
#  founder_id       :integer
#  company_name     :text
#  email_address    :text
#  password_digest  :text
#  location         :text
#  website          :text
#  profile_picture  :text
#  description      :text
#  industry         :text
#  capital_required :text
#  equity_share     :text
#  video            :text
#  image_one        :text
#  image_two        :text
#  image_three      :text
#  image_four       :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Founder < ActiveRecord::Base

  has_secure_password
  has_many :swipes
  
end

app/controllers/founders_controller.rb
class FoundersController < ApplicationController
  before_action :set_founder, only: [:show, :edit, :update, :destroy]

  # GET /founders
  # GET /founders.json
  def index
    @founders = Founder.all.shuffle
  end

  # GET /founders/1
  # GET /founders/1.json
  def show
    
  end

  # GET /founders/new
  def new
    @founder = Founder.new
  end

  # GET /founders/1/edit
  def edit
  end

  # POST /founders
  # POST /founders.json
  def create
    @founder = Founder.new(founder_params)

    unless !params[:file] || params[:file] == ""
    image = Cloudinary::Uploader.upload( params[:file] )
    @founder.profile_picture = image["url"]
    end

    unless !params[:video] || params[:video] == ""
    video = Cloudinary::Uploader.upload( params[:video], :resource_type => :video)
    @founder.video = video["url"]
    end

    unless !params[:founder][:image_one] || params[:founder][:image_one] == ""
    image_one = Cloudinary::Uploader.upload( params[:founder][:image_one] )
    @founder.image_one = image_one["url"]
    end

    unless !params[:founder][:image_two] || params[:founder][:image_two] == ""
    image_two = Cloudinary::Uploader.upload( params[:founder][:image_two] )
    @founder.image_two = image_two["url"]
    end

    unless !params[:founder][:image_three] || params[:founder][:image_three] == ""
    image_three = Cloudinary::Uploader.upload( params[:founder][:image_three] )
    @founder.image_three = image_three["url"]
    end

    unless !params[:founder][:image_four] || params[:founder][:image_four] == ""
    image_four = Cloudinary::Uploader.upload( params[:founder][:image_four] )
    @founder.image_four = image_four["url"]
    end

    respond_to do |format|
      if @founder.save
        format.html { redirect_to @founder, notice: 'Founder was successfully created.' }
        format.json { render :show, status: :created, location: @founder }
      else
        format.html { render :new }
        format.json { render json: @founder.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /founders/1
  # PATCH/PUT /founders/1.json
  def update
    unless params[:file] == ""
      image = Cloudinary::Uploader.upload( params[:file] ) 
      @founder.profile_picture = image["url"]
    end

    unless !params[:video] || params[:video] == ""
      video = Cloudinary::Uploader.upload( params[:video], :resource_type => :video)
      @founder.video = video["url"]
    end

    unless !params[:founder][:image_one] || params[:founder][:image_one] == ""
      image_one = Cloudinary::Uploader.upload( params[:founder][:image_one] )
      @founder.image_one = image_one["url"]
    end

    unless !params[:founder][:image_two] || params[:founder][:image_two] == ""
      image_two = Cloudinary::Uploader.upload( params[:founder][:image_two] )
      @founder.image_two = image_two["url"]
    end

    unless !params[:founder][:image_three] || params[:founder][:image_three] == ""
      image_three = Cloudinary::Uploader.upload( params[:founder][:image_three] )
      @founder.image_three = image_three["url"]
    end

    unless !params[:founder][:image_four] || params[:founder][:image_four] == ""
      image_four = Cloudinary::Uploader.upload( params[:founder][:image_four] )
      @founder.image_four = image_four["url"]
    end

    respond_to do |format|
      if @founder.update(founder_params)
        format.html { redirect_to @founder, notice: 'Founder was successfully updated.' }
        format.json { render :show, status: :ok, location: @founder }
      else
        format.html { render :edit }
        format.json { render json: @founder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /founders/1
  # DELETE /founders/1.json
  def destroy
    @founder.destroy
    respond_to do |format|
      format.html { redirect_to founders_url, notice: 'Founder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    swipe = Swipe.new
    swipe.founder_id = params[:id]
    swipe.investor_id = @current_investor.id
    swipe.favourite = true
    swipe.save
    render :json => { :status => 'hunkydory' }
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_founder
      @founder = Founder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def founder_params
      params.require(:founder).permit(:name, :founder_id, :company_name, :email_address, :password, :password_confirmation, :website, :profile_picture, :description, :industry, :capital_required, :equity_share, :video, :image_one, :image_two, :image_three, :image_four)
    end
end

app/helpers/founders_helper.rb
module FoundersHelper
end

app/views/founders/_form.html.erb
<%= form_for(@founder, :html => { :multipart => true }) do |f| %>
  <% if @founder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@founder.errors.count, "error") %> prohibited this founder from being saved:</h2>

      <ul>
      <% @founder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :company_name %><br>
    <%= f.text_area :company_name %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.text_area :email_address %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_area :website %>
  </div>
    <div class="field">
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </div>
  <div class="field">
    <%= f.label :profile_picture %><br>
    <%= f.cl_image_upload :profile_picture %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :industry %><br>
    <%= f.select :industry, ['Agriculture and Mining', 'Business Services', 'Computer and Electronics','Consumer Services', 'Education', 'Energy and Utilities', 'Financial Services', 'Government', 'Health, Pharmaceuticals, and Biotech', 'Manufacturing', 'Media and Entertainment', 'Non-profit', 'Real Estate and Construction', 'Retail', 'Software and Internet'] %>
  </div>

  <div class="field">
    <%= f.label :capital_required %><br>
    <%= f.text_area :capital_required %>
  </div>
  <div class="field">
    <%= f.label :equity_share %><br>
    <%= f.text_area :equity_share %>
  </div>
  <div class="field">
    <%= label_tag :video %><br>
    <%= file_field_tag :video %>
  </div>
  <div class="field">
    <%= f.label :image_one %><br>
    <%= f.file_field :image_one %>
  </div>
  <div class="field">
    <%= f.label :image_two %><br>
    <%= f.file_field :image_two %>
  </div>
  <div class="field">
    <%= f.label :image_three %><br>
    <%= f.file_field :image_three %>
  </div>
  <div class="field">
    <%= f.label :image_four %><br>
    <%= f.file_field :image_four %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/founders/edit.html.erb
<div class="container">
  <div class="login-signup">
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="home">
        <div class="row">

          <div class="col-sm-6 mobile-pull">
              <article role="login">
                <h3 class="text-center"><i class="fa fa-lock"></i>Update Founder</h3>

                  <%= form_for(@founder, :method => :put) do |f| %> 

                <div class="form-group">
                  <%= f.label :profile_picture %><br>
                  <%= f.cl_image_upload :profile_picture %>
                </div>

                <div class="form-group">
                  <%= f.label :industry %><br>
                  <%= f.select :industry, ['Agriculture and Mining', 'Business Services', 'Computer and Electronics','Consumer Services', 'Education', 'Energy and Utilities', 'Financial Services', 'Government', 'Health, Pharmaceuticals, and Biotech', 'Manufacturing', 'Media and Entertainment', 'Non-profit', 'Real Estate and Construction', 'Retail', 'Software and Internet'] %>
                </div>

                  <div class="form-group">
                    <%= f.text_field :name, :placeholder => "Name", class: "form-control" %> 
                  </div>
                  <div class="form-group">
                    <%= f.text_field :company_name, :placeholder => "Company Name", class: "form-control" %> 
                  </div>
                  <div class="form-group">
                    <%= f.text_field :website, :placeholder => "Website", class: "form-control" %> 
                  </div>
                   <div class="form-group">
                    <%= f.text_field :capital_required, :placeholder => "Capital Required", class: "form-control" %> 
                  </div>
                   <div class="form-group">
                    <%= f.text_field :equity_share, :placeholder => "Equity Share", class: "form-control" %> 
                  </div>
        
                  <div class="form-group">
                    <%= f.email_field :email_address, :placeholder => "Email", class: "form-control" %> 
                  </div>
                  <div class="form-group">
                    <%= f.password_field :password, :placeholder => "Password", class: "form-control"%> 
                  </div>
                  <div class="form-group">
                    <%= f.password_field :password_confirmation, :placeholder => "Password Confirmation", class: "form-control"%> 
                  </div>

                  <div class="form-group">
                    <%= f.submit "UPDATE", class: "btn btn-submit btn-success btn-block" %>
                  </div>
                    <% end %>

              </article>
            </div>

          </div>
          <!-- end of row -->
        </div>
        <!-- end of home -->
  </div>
</div>

app/views/founders/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>jTinder Touch Slider</title>

</head>
<body>
    <!-- start padding container -->
    <div class="wrap">
        <!-- start jtinder container -->
        <div id="tinderslide">
            <ul>
              <% @founders.each do |founder| %>

                <li class="pane5" data-founder-id="<%= founder.id %>">
                    <div class="img">
                      <img src="<%= founder.profile_picture %>" alt="">
                    </div>
                    <div class="details">
                      <div><%= founder.company_name %></div>
                      <div>About: <%= founder.description %></div>
                      <div>Industry: <%= founder.industry %></div>
                      <div>Capital required: <%= founder.capital_required %></div>
                      <div>Equity share: <%= founder.equity_share %></div>
                      <div>Website: <%= founder.website %></div>
                    </div>

                    <div class="like"></div>
                    <div class="dislike"></div>
                </li>
               
            </ul>
        </div>
        <!-- end jtinder container -->
    </div>
    <!-- end padding container -->

    <!-- jTinder trigger by buttons  -->
    <div class="actions">
        <a href="#" class="dislike"><i></i></a>
        <a href="#" class="like"><i></i></a>
    </div>

    <!-- jTinder status text  -->

    <div id="status"></div>

    
<div class="container">
    <div class="row">
        <ul class="thumbnails">
            <div class="col-md-4">
                <div class="thumbnail">
                    <img src="http://placehold.it/320x200" alt="ALT NAME" class="img-responsive" />
                    <div class="caption">
                         <h3><div><%= founder.company_name %></div></h3>
                        <p><div>About: <%= founder.description %></div>
                      <div>Industry: <%= founder.industry %></div>
                      <div>Capital required: <%= founder.capital_required %></div>
                      <div>Equity share: <%= founder.equity_share %></div>
                      <div>Website: <%= founder.website %></div></p>
                    </div>
                </div>
            </div>
 <% end %>
        </ul>
    </div>
</div>


</body>
</html>
  

app/views/founders/new.html.erb
<div class="container">
  <div class="login-signup">
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="home">
        <div class="row">

          <div class="col-sm-6 mobile-pull">
              <article role="login">
                <h3 class="text-center"><i class="fa fa-lock"></i>Founder Registration</h3>

                  <%= form_for(:session, url: founder_login_path) do |f| %> 

                <div class="form-group">
                  <%= f.label :profile_picture %><br>
                  <%= f.cl_image_upload :profile_picture %>
                </div>

                <div class="form-group">
                  <%= f.label :industry %><br>
                  <%= f.select :industry, ['Agriculture and Mining', 'Business Services', 'Computer and Electronics','Consumer Services', 'Education', 'Energy and Utilities', 'Financial Services', 'Government', 'Health, Pharmaceuticals, and Biotech', 'Manufacturing', 'Media and Entertainment', 'Non-profit', 'Real Estate and Construction', 'Retail', 'Software and Internet'] %>
                </div>

                  <div class="form-group">
                    <%= f.text_field :name, :placeholder => "Name", class: "form-control" %> 
                  </div>
                  <div class="form-group">
                    <%= f.text_field :company_name, :placeholder => "Company Name", class: "form-control" %> 
                  </div>
                  <div class="form-group">
                    <%= f.text_field :website, :placeholder => "Website", class: "form-control" %> 
                  </div>
                   <div class="form-group">
                    <%= f.text_field :capital_required, :placeholder => "Capital Required", class: "form-control" %> 
                  </div>
                   <div class="form-group">
                    <%= f.text_field :equity_share, :placeholder => "Equity Share", class: "form-control" %> 
                  </div>
        
                  <div class="form-group">
                    <%= f.email_field :email_address, :placeholder => "Email", class: "form-control" %> 
                  </div>
                  <div class="form-group">
                    <%= f.password_field :password, :placeholder => "Password", class: "form-control"%> 
                  </div>
                  <div class="form-group">
                    <%= f.password_field :password_confirmation, :placeholder => "Password Confirmation", class: "form-control"%> 
                  </div>

                  <div class="form-group">
                    <%= link_to 'REGISTER', founder_signup_path, class: "btn btn-success btn-block" %>
                  </div>
                    <div class="actions">
    <%= f.submit %>
  </div>

                    <% end %>

              </article>
            </div>

          </div>
          <!-- end of row -->
        </div>
        <!-- end of home -->
  </div>
</div>

app/views/founders/show.html.erb
<div class="container">
  <div class="login-signup">
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="home">
        <div class="row">

          <div class="col-sm-6 mobile-pull">
              <article role="login">
                <h3 class="text-center"><i class="fa fa-lock"></i>My Profile</h3>
            
                <center>
                  <a href="#aboutModal" data-toggle="modal" data-target="#myModal"><img src="<%= @founder.profile_picture %>" name="aboutme" width="140" height="140" class="img-circle"></a>
                  <h1><%= @founder.name %></h1>
                  <h1><%= @founder.company_name %></h1>
                  <h1>Description: <%= @founder.description %></h1>
                  <h1>Industry: <%= @founder.industry %></h1>
                  <h1>Capital required: <%= @founder.capital_required %></h1>
                  <h1>Equity share: <%= @founder.equity_share %></h1>
                  <%= link_to 'Edit', edit_founder_path(@founder) %>
                </center>
            </article>
          </div>
        </div>
<!-- end of row -->
      </div>
<!-- end of home -->
    </div>
  x</div>
</div>




<!-- <p>
  <strong>Video:</strong>
  <%= @founder.video %>
</p>
<br>
<p>
  <strong>Image one:</strong>
  <%= @founder.image_one %>
</p>
<br>
<p>
  <strong>Image two:</strong>
  <%= @founder.image_two %>
</p>
<br>
<p>
  <strong>Image three:</strong>
  <%= @founder.image_three %>
</p>
<br>
<p>
  <strong>Image four:</strong>
  <%= @founder.image_four %>
</p>
<br>
 -->