config/routes.rb
Rails.application.routes.draw do
  resources :swipes
  resources :investors
  resources :founders
  resources :pages

  get '/favourites' => 'swipes#index'

  # root :to => 'sessions#new'
  root :to => 'founders#index'
  
  get '/login' => 'sessions#new'

  get '/investor_signup' => 'investors#new'

  get '/founder_signup' => 'founders#new'

  post '/investor_login' => 'sessions#investor_login'
  post '/founder_login' => 'sessions#founder_login'

  delete '/investor_logout' => 'sessions#investor_logout'
  delete '/founder_logout' => 'sessions#founder_logout'

  post '/founders/:id/like' => 'founders#like'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlickseedV2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>   
    </div>

          <div class="brand">
        <a class="navbar-brand" href="/">Flickseed</a>
      </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <button type="button" class="btn btn-default btn-lg" >
              <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </button>
          </a>

          <ul class="dropdown-menu">
                        <% if @current_founder.present? %> 
              <ul> 
                <li> Hi, <%= @current_founder.email_address %></li> 
                <li><%= link_to "My profile", founder_path(@current_founder) %></li> 
                <li><%= link_to "Log out", '/founder_logout', method: "delete" %></li> 
              </ul> 
            <% elsif @current_investor.present? %> 
              <ul> 
                <li> Hi, <%= @current_investor.email_address %></li> 
                <li><%= link_to "My profile", investor_path(@current_investor) %></li> 
                <li><%= link_to "Favourites", favourites_path %></li> 
                <li><%= link_to "Log out", '/investor_logout', method: "delete" %></li>
              </ul> 
            <% else %>       
          </ul>
        </li>
      </ul>

            <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "LOGIN", '/login' %></a>
            </li> 
           <% end %>  


      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


  <%= yield %>

</body>
</html>